name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: | # Pipe character is used to write a string in multiple lines as it adds a new`line character at the end of each line
          node -v
          npm -v