name: Workflow commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up an error message
        run: echo "::error::Missing semicolon"

      - name: Setting up an error message with parameters
        run: echo "::error title:Error title,file=app.js,line=2,col=5::Missing Semicolon"

      - name: Setting up an debug message with parameters
        run: echo "::debug title:Debug title,file=app.js,line=2,col=5::Missing Semicolon"

      - name: Setting up an warning message with parameters
        run: echo "::warning title:Warning title,file=app.js,line=2,col=5::Missing Semicolon"

      - name: Setting up an notice message with parameters
        run: echo "::notice title:Notice title,file=app.js,line=2,col=5::Missing Semicolon"

      - name: Group of logs
        run: |
          echo "::group::Grouping logs"
          echo "This is the first line"
          echo "This is the second line"
          echo "::endgroup::"
      - name: Masking a value
        run: echo "::add-mask::mysecret"
      - name: Echo a secret
        run: echo mysecret
